[project]
name = "django-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["django"]

[tool.pyright]
venvPath = "."
venv = ".venv"
include = ["src", "tests"]
